# narrowly focused ansible deployment playbook to configure ddclient
---
- name: Configure Server
  hosts: all
  become: true

  tasks:
    - name: Configure sshd
      ansible.builtin.import_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
      when: ansible_connection != 'local'

    - name: Configure Firewall Allowlist
      ansible.posix.firewalld:
        immediate: true
        permanent: true
        service: "{{ item }}"
        state: enabled
        zone: FedoraServer
      loop:
        - http
        - https
