# narrowly focused ansible deployment playbook to prepare server for hosting our sites
---
- name: Configure Server
  hosts: all
  become: true

  tasks:
    - name: Configure sshd
      ansible.builtin.import_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
      when: ansible_connection != 'local'

    - name: Permit rootless users to listen on low ports
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: 80
        state: present

    - name: Configure Firewall Allowlist
      ansible.posix.firewalld:
        immediate: true
        permanent: true
        port: "{{ item }}"
        state: enabled
        zone: FedoraServer
      loop:
        - 80/tcp
        - 443/tcp

    - name: Install Required Packages
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - podman
