---
- name: Import sshguard.yml
  ansible.builtin.import_tasks: sshguard.yml

- name: Include add_users.yml
  ansible.builtin.include_tasks: add_users.yml
  loop_control:
    loop_var: _sshd__allow_user
  loop: "{{ sshd__allow_users }}"

- name: Import harden.yml
  ansible.builtin.import_tasks: harden.yml
  notify:
    - "reload_sshd"
