---
- name: install sshguard
  become: true
  ansible.builtin.dnf:
    name: sshguard
    state: latest
  tags: skip_ansible_lint

- name: enable sshguard allowlist
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sshguard.conf"
    backup: true
    regex: "^(#)?{{ _sshd__sshguard_item }}"
    line: "{{ _sshd__sshguard_item }}"
    state: present
  loop_control:
    loop_var: _sshd__sshguard_item
  loop:
    - "WHITELIST_FILE=/etc/sshguard.whitelist"

- name: allowlist some addresses in sshguard
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sshguard.whitelist"
    backup: true
    regex: "^(#)?{{ _sshd__sshguard_item }}"
    line: "{{ _sshd__sshguard_item }}"
    state: present
  loop_control:
    loop_var: _sshd__sshguard_item
  loop: "{{ sshd__sshguard_allowlist if sshd__sshguard_allowlist is iterable else [] }}"

- name: start and enable sshguard
  become: true
  ansible.builtin.service:
    name: sshguard
    enabled: true
    state: started
